### PR TITLE
Fix bug in diff algorithm

### PR DESCRIPTION
**Pull request by gzgreg**
This looks like a minor bug in the algorithm: fixing it improves performance on a few of the test cases. Has the side effect of occasionally switching the order of added and removed pieces.

### CODE REVIEW

**Comment by ataillefer** [comment]
Hi,

Could you please explain the bug in detail, describe in what way the performance of some of the test cases is improved (metrics?) and mostly why it switches the order and how this change can be considered as OK from a functional point of view?

We have some code running unit tests depending on DaisyDiff. When I run them against your fork they fail, obviously because I would need to apply the same changes about order you've done in the expected HTML of the DaisyDyff tests. So this means that the behavior is changed in the rendered UI.

Unless this bug is fully qualified and justifies such a change in the expected behavior to be fixed we cannot merge the PR as it is.

Thanks

**Comment by gzgreg** [comment]
Sure, a little more explanation of what I believe the bug is:

The significant change is at `TextNodeComparator.java` at line 266. Essentially, the first deleted node always gets inserted near the beginning of the changed range, even if the changes occur later, because nextLeaf is incorrectly defined to be near the beginning of the changed range initially (although the rest of the code assumes that it is at the end). This means that the first deleted node for a particular change can be inserted in the wrong place, and the changes may also propagate due to the new nextLeaf having the wrong parent as well.

The test cases in Daisydiff that display this behavior are `Tables/39 change columns` and `General/Minimal/06 Lists ins del items`. For the first one, the deleted word "Sample" is moved to the wrong cell (before "new column", which is where the changed range begins). For the second, the deleted words "This is" are again placed before the changed range, instead of after it where they ought to be (since the new words are inserted before the relevant list element).

Changing the nextLeaf's initial value to be at the end of the range instead of the beginning fixes these two test cases.

I will try to work out why the order is changing as well.

If you have any other questions let me know!

**Comment by gzgreg** [comment]
Alright, I've made a new change that removes the order switching for the DaisyDiff test cases.

**Comment by ataillefer** [comment]
Thanks, your latest commit indeed fixes the ordering issue in our unit tests when relying on your branch.
Just merged it.

I've also released the 1.2-NX4 version.

**Pull request merged**
